### ISSUE TITLE
Converting JSON DM Plan into a document

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#5]
Compile JSON into some very general document format, which Pandoc can transform into "anything".

## Prerequisites:
- #4

**Comment by perglr** [comment]
Compile JSON into some very general document format, which Pandoc can transform into "anything"

**Comment by perglr** [comment]
+1

**Comment by MarekSuchanek** [comment]
Working on it in [DataStewardshipWizard/dsw-server - feature/dmp-transform](https://github.com/DataStewardshipWizard/dsw-server/tree/feature/dmp-transform)

**Comment by MarekSuchanek** [comment]
Initial version should be ready since https://github.com/DataStewardshipWizard/dsw-server/commit/895d94cdb341f959c04355c3ccdf463208999e51. 

- Main part is HTML ([Blaze](http://hackage.haskell.org/package/blaze-html)) + CSS ([Clay](http://hackage.haskell.org/package/clay))
- Common interface `dmpTransform` returns ByteString (UTF-8 encoding) for given filled KM and selected export type
  - If it is HTML type -> just HTML+CSS in one file (using `<style>` tag)
  - Otherwise [Pandoc](http://hackage.haskell.org/package/pandoc) is called on the HTML+CSS to produce different format (RTF, RST, Markdown, etc.)
- For PDF, I suggest client-side generation in browser with something like [jsPDF](https://mrrio.github.io), there is also [elm-pdf](https://github.com/AionDev/elm-pdf) for our frontend if necessary...

There is one bad thing, Pandoc building (as dependencies) is quite long and for new version I had to edit `stack.yml`.

**Comment by touwwouter** [comment]
It would be great if a local installation of dsw-server can use local style files (e.g. LaTeX template for PDF or CSS for HTML) for customization of Pandoc output.

**Comment by touwwouter** [comment]
Also, given the potential length of the questionnaires, it would be great if a particular question can be looked up easily both in the report/document as in the questionnaire online. Use question numbers from the km?

**Comment by MarekSuchanek** [comment]
_Update_: separate package ("facade") for HTML to other format conversion is released on Hackage (see https://github.com/MarekSuchanek/FromHTML). I will now incorporate it in dsw-server.

**Comment by MarekSuchanek** [comment]
_Update_: Changes incorporated in https://github.com/DataStewardshipWizard/dsw-server/tree/feature/dmp-transform

**Comment by MarekSuchanek** [comment]
@touwwouter Regarding older "IDs" in KM - we are going to abandon them. Although those are human readable and usable (vs. UUIDs), they come with problems:

- editing by hand = easy to make mistake
- they are often not ordered, so you have to search anyway
- trying to do something like "1,2,3,31,32,4,99" is not really good and could be understood in different ways

Human-readable IDs can be then of course computed by order and hierarchy (e.g., Question 1c.2a.4, or similar).

**Comment by MarekSuchanek** [comment]
_Update_: Together with @vknaisl, we've merged https://github.com/DataStewardshipWizard/dsw-server/pull/6. Now just extending the client and deploying should be done...

**Comment by vknaisl** [comment]
Deployed to staging
