### ISSUE TITLE
DSW to public Docker Hub

### ISSUE THREAD

**Issue by MarekSuchanek** [DataStewardshipWizard/dsw-common#77]
- [x] Put DSW client to https://hub.docker.com
- [x] Put DSW server to https://hub.docker.com

**Comment by janslifka** [comment]
We also need to use version as other docker images do. E.g. if we publish version 2.1.3 the following tags should be used for the image: 2.1.3, 2.1, 2 and latest. It is now important so that people can target specific versions and keep compatible frontend and backend.

It would be also nice to have a matrix of compatible frontend / backend versions somewhere in the docs.

**Comment by vknaisl** [comment]
Perhaps create a new issue? I would close this issue as far as the main purpose was accomplished

**Comment by janslifka** [comment]
@vknaisl I finished that already.
