### ISSUE TITLE
Questionnaire module selection and merging

### ISSUE THREAD

**Issue by touwwouter** [DataStewardshipWizard/dsw-common#79]
The knowledge model allows domain/instrument/application/context-specific or 'local' questions than can be plugged into the 'core' knowledge model.

As a user in an organization where many different local knowledge models are maintained, I'd like to select questionnaire modules and have them merged into a single questionnaire.

**Comment by MarekSuchanek** [comment]
It can be done basically by selecting multiple knowledge models and giving them priority (order in which events should be applied). Backend should find nearest common root, apply its events and then in correct order the others. 

Maybe it would be easier to provide way to create knowledge model as merge of multiple packages with ability to edit it. Something like multiple (prioritized) inheritance instead of having just single parent KM package.

**Comment by vknaisl** [comment]
It's possible but it will be a bigger issue that it seems to be - it has to be considered how it will affect migration process (a process when the parent of your knowledge is upgraded and you want have these changes in your knowledge model)

**Comment by touwwouter** [comment]
How do you currently handle this when combining the [core](https://github.com/DataStewardshipWizard/ds-km/tree/master/datamodel/core) and [local](https://github.com/DataStewardshipWizard/ds-km/tree/master/datamodel/local) modules of ds-km?

**Comment by MarekSuchanek** [comment]
Currently [km2events](https://github.com/DataStewardshipWizard/km2events) just translates the core to events for the Wizard. But soon (hopefully) it will handle localizations to be customizations with parent knowledge model set to core. The processing how events are applied in a row was implemented by @vknaisl.

**Comment by vknaisl** [comment]
Moved to Jira: https://ds-wizard.atlassian.net/browse/DSW-88
