### ISSUE TITLE
Add the core FAIRness metrics questions

### ISSUE THREAD

**Issue by perglr** [DataStewardshipWizard/dsw-common#91]
https://github.com/FAIRMetrics/Metrics/blob/1.0.2/Evaluation_Of_Metrics/Supplementary%20Information_%20FM%20Evaluation%20Results.pdf

Part of #7.

**Comment by MarekSuchanek** [comment]
I've created a new KM in dsw.fairdata.solutions with 14 questions from FAIR metrics, but it is a bit clumsy now.

1. Some references should be completed after #62 
2. Metrics should be attached #85 
3. There is also need of #87 because there are metrics that need to ask for multiple values of different types (e.g., URL and true/false or URL and IRIs)

**Comment by MarekSuchanek** [comment]
This is done and will be improved with #92
